name: 'dispatch_test'
run-name: 'dispatch_test[${{ github.event.client_payload.uuid }}]'

on:
  repository_dispatch:
    types:
      - 'test'

jobs:
  plan:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744' # ratchet:actions/checkout@v3

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@a1502cd9e758c50496cc9ac5308c4843bcd56d36' # ratchet:hashicorp/setup-terraform@v3

      - name: 'Test Plan'
        env:
          UUID: '${{ github.event.client_payload.uuid }}'
        shell: 'bash'
        run: |-
          terraform init -input=false -no-color -lock-timeout=15m
          terraform plan -input=false -no-color -lock-timeout=15m
