name: 'dispatch_test'
run-name: 'dispatch_test[${{ github.event.client_payload.uuid }}]'

on:
  repository_dispatch:
    types:
      - 'test'

jobs:
  plan:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744' # ratchet:actions/checkout@v3

      - name: 'Setup OPA'
        uses: 'open-policy-agent/setup-opa@v2'
        with:
          version: 'latest'

      - name: 'Validate'
        env:
          UUID: '${{ github.event.client_payload.uuid }}'
        run: |-
          echo "[START-${UUID}]"
          OUT=$(opa eval --bundle policy --input $GITHUB_EVENT_PATH --format values --fail-defined "data.guardian.deny[message]")
          EXIT=$(echo $?)
          echo $OUT
          echo "[END-${UUID}]"
          exit $EXIT

      - name: 'Setup Terraform'
        uses: 'hashicorp/setup-terraform@a1502cd9e758c50496cc9ac5308c4843bcd56d36' # ratchet:hashicorp/setup-terraform@v3

      - name: 'Command'
        env:
          UUID: '${{ github.event.client_payload.uuid }}'
          COMMAND: '${{ github.event.client_payload.command }}'
        shell: 'bash'
        run: |-
          set -x
          echo "[START-${UUID}]"
          terraform -chdir="terraform" init -input=false -no-color
          $COMMAND
          echo "[END-${UUID}]"
