name: 'dispatch_test'
run-name: 'dispatch_test - [${{ github.event.action }}]'

on:
  repository_dispatch:
    types:
      - 'test_plan'
      - 'test_output'

jobs:
  plan:
    if: |
      github.event.action == 'test_plan'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744' # ratchet:actions/checkout@v3

      - name: 'Test Plan'
        shell: 'bash'
        run: |-
          echo "Test Plan!"

  outputs:
    if: |
      github.event.action == 'test_outputs'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744' # ratchet:actions/checkout@v3

      - name: 'Test Outputs'
        shell: 'bash'
        run: |-
          echo "Test Outputs!"
