name: 'dispatch_test'
run-name: 'dispatch_test[${{ github.event.client_payload.uuid }}]'

on:
  repository_dispatch:
    types:
      - 'test'

jobs:
  plan:
    if: |
      github.event.client_paylod.command == 'plan'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744' # ratchet:actions/checkout@v3

      - name: 'Test Plan'
        shell: 'bash'
        run: |-
          echo "Sleep 30"
          echo "Test Plan!"

  outputs:
    if: |
      github.event.client_paylod.command == 'output'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744' # ratchet:actions/checkout@v3

      - name: 'Test Outputs'
        shell: 'bash'
        run: |-
          echo "Sleep 30"
          echo "Test Outputs!"
