name: 'dispatch_test'
run-name: 'dispatch_test[${{ github.event.client_payload.uuid }}]'

on:
  repository_dispatch:
    types:
      - 'test'

jobs:
  plan:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744' # ratchet:actions/checkout@v3

      - name: 'Validate'
        env:
          KIND: '${{ github.event.client_payload.kind }}'
          UUID: '${{ github.event.client_payload.uuid }}'
        shell: 'bash'
        run: |-
          echo "[START-${UUID}]"
          if [[ $KIND == "allow" ]]; then
            echo "allowed"
            echo "[END-${UUID}]"
            exit 0
          else
            echo "denied"
            echo "[END-${UUID}]"
            exit 1
          fi

      - name: 'Setup Terraform'
        uses: 'hashicorp/setup-terraform@a1502cd9e758c50496cc9ac5308c4843bcd56d36' # ratchet:hashicorp/setup-terraform@v3

      - name: 'Command'
        env:
          UUID: '${{ github.event.client_payload.uuid }}'
          COMMAND: '${{ github.event.client_payload.command }}'
        shell: 'bash'
        run: |-
          echo "[START-${UUID}]"
          $COMMAND
          echo "[END-${UUID}]"
