name: 'Test'
on:
  pull_request:
  workflow_dispatch:
jobs:
  init:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
    outputs:
      paths: ${{ steps.set-matrix.outputs.paths }}
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c' # ratchet:actions/checkout@v3
      - id: 'set-matrix'
        name: 'Set Matrix'
        run: |-
          echo "paths=test" >> $GITHUB_OUTPUT

  test:
    strategy:
      matrix:
        version: 
          - '10'
          - '12'
    needs:
      - 'init'
    if: ${{ needs.init.result == 'success' }}
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c' # ratchet:actions/checkout@v3
      - name: 'Echo'
        run: echo "${{ github.job }}"
      - name: 'Success'
        run: exit 0
      - name: 'Failure'
        run: exit 1

  cleanup:
    needs:
      - 'init'
      - 'test'
    if: ${{ always() }}
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c' # ratchet:actions/checkout@v3
      - name: 'Success'
        run: exit 0
      - name: 'Failure'
        run: exit 1

  success:
    needs:
      - 'init'
      - 'test'
      - 'cleanup'
    if: ${{ always() }}
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Success'
        run: exit 0

