name: 'want-lgtm-all'

on:
  pull_request:
    types:
      - assigned
      - unassigned
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review
      - review_requested
      - review_request_removed
  pull_request_review:
    types:
      - submitted
      - dismissed
      - edited
  workflow_call:
  workflow_dispatch:

permissions:
  pull-requests: 'read'

jobs:
  presubmit:
    runs-on: 'ubuntu-latest'
    steps:
      - id: 'validate-reviewers'
        if: '${{ github.event.pull_request }}'
        uses: 'actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410' # ratchet:actions/github-script@v6
        with:
          script: |-
            const body = context.payload.pull_request.body || "";

            // if pr body does not contain want_lgtm_all, exit gracefully
            if (!body.match(/want_lgtm_all/gim)) {
              console.log("PR body does not contain want_lgtm_all");
              return;
            }

            let activeReviewers = await github.rest.pulls.listRequestedReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });

            const usersStillNeedingApproval = activeReviewers.data.users.map(
              (u) => u.login
            );

            console.log(
              "Users still needing approval: " + JSON.stringify(usersStillNeedingApproval)
            );

            const reviews = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });

            console.log(
              "Completed reviews: " + JSON.stringify(reviews.data.map((r) => r.user?.login))
            );

            if (usersStillNeedingApproval.length > 0) {
              core.setFailed(
                "Waiting on Approval from " + usersStillNeedingApproval.join(", ")
              );
              return;
            }

            // get the filename for this workflow
            var workflowFilename = process.env.GITHUB_WORKFLOW_REF.split("@")[0].split("/").pop();

            // when a pull_request_review is submitted, and all required reviewers have approved
            // we need to re-trigger any previously failed pull_request event for our workflow
            if (context.eventName == "pull_request_review") {
              // Get workflows
              let workflows = await github.rest.actions.listWorkflowRuns({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: workflowFilename,
                branch: context.payload.pull_request.head.ref,
                event: "pull_request",
              });

              let unsuccessfulRuns = workflows.data.workflow_runs
                .filter((w) => w.conclusion != "success")
                .filter((w) => w.pull_requests?.map((p) => p.number).includes(context.issue.number))
                .sort((x) => x.run_number);
              
              console.log(unsuccessfulRuns);

              if (unsuccessfulRuns.length > 0) {
                let t = await github.rest.actions.reRunWorkflow({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  run_id: unsuccessfulRuns[0].id,
                });
              }
            }
